Update GetDownloadCount.yml

diff --git a/.github/workflows/GetDownloadCount.yml b/.github/workflows/GetDownloadCount.yml
--- a/.github/workflows/GetDownloadCount.yml
+++ b/.github/workflows/GetDownloadCount.yml
@@ -18,14 +18,15 @@ jobs:
       - name: Fetch Download Count
         id: fetch_downloads
         run: |
+          # Fetch the releases
           releases=$(curl -s https://api.github.com/repos/shupershuff/diablo2rloader/releases)
 
           # Debug: Print releases to check the response
-          #echo "Releases data: $releases"
+          echo "Releases data: $releases" > releases.json
 
-          # Check if releases is empty or not valid JSON
-          if [ -z "$releases" ] || ! echo "$releases" | jq empty; then
-            echo "Error: No releases found or invalid JSON response."
+          # Validate JSON format and check for errors
+          if ! jq empty releases.json > /dev/null 2>&1; then
+            echo "Error: Invalid JSON response."
             exit 1
           fi
 
@@ -33,7 +34,7 @@ jobs:
           max_download_count=0
           release_with_max_downloads=""
 
-          # Iterate through each release using a for loop to avoid subshell issues
+          # Iterate through each release using a for loop
           for release in $(echo "$releases" | jq -c '.[]'); do
             release_data=$(echo "$release" | jq '.')
             release_name=$(echo "$release_data" | jq -r '.tag_name')
@@ -56,6 +57,8 @@ jobs:
           # Assign to GitHub output
           echo "download_count=$max_download_count" >> $GITHUB_OUTPUT
           echo "release_with_max_downloads=$release_with_max_downloads" >> $GITHUB_OUTPUT
+
+
 
       - name: Update JSON File
         run: |
